stages:
  - test
  - package
  - packagetest
  - deploy

test:debian:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install python3-setuptools ca-certificates python3-pip python3-mock -qy
    - python3 setup.py test
  tags:
    - debian

test:archlinux:
  stage: test
  script:
    - pacman -Syu python-setuptools python-pip python-mock --noconfirm
    - python setup.py test
  tags:
    - archlinux

package:debian:
  stage: package
  script:
    - apt-get update -qy
    - apt-get install -y python-all python3-stdeb dh-python
    - rm -rf "./deb_dist"
    - export DEB_BUILD_OPTIONS=nocheck
    - python3 setup.py --command-packages=stdeb.command bdist_deb
  tags:
    - debian

  artifacts:
    paths:
      - deb_dist/*.deb
    expire_in: 1d

package:archlinux:
  stage: package
  script:
    - pacman -Sy sudo fakeroot systemd binutils python-setuptools --noconfirm
    - useradd -m -G users -s /bin/bash package
    - chown -R package:users archlinux
    - cd archlinux
    - sudo -H -u package makepkg -f
  tags:
    - archlinux

  artifacts:
    paths:
      - archlinux/python-cron-descriptor*
    expire_in: 1d

packagetest:debian:
  stage: packagetest
  script:
    - apt-get update -qy
    - cd deb_dist
    - apt install ./*.deb -qy
  tags:
    - debian
  dependencies:
    - package:debian


packagetest:archlinux:
  stage: packagetest
  script:
    - pacman -Sy
    - cd archlinux
    - pacman -U python-cron-descriptor*.pkg.tar.zst --noconfirm
  tags:
    - archlinux
  dependencies:
    - package:archlinux

repoupdate:
  stage: deploy
  variables:
    TWINE_USERNAME: Salamek
  before_script:
    # SSH
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y
    - apt-get install twine python-setuptools -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/any/python-cron-descriptor*.pkg.tar.zst'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/python3-cron-descriptor*.deb'
    - scp archlinux/python-cron-descriptor*.pkg.tar.zst www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/any
    - scp deb_dist/*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - ssh www-data@repository '/var/www/repository.salamek.cz/deb-pub-update.sh'
    - ssh www-data@repository '/var/www/repository.salamek.cz/arch-pub-update.sh'
  
    # PyPi update
    - python3 setup.py sdist bdist_wheel
    - twine upload dist/*
  dependencies:
    - package:archlinux
    - package:debian
  tags:
    - debian
  only:
    - tags
